name: "Build Load Generator Image"
on:
  push:
    branches:
      - main 
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker build -t expelliarmus625/loadgenerator ./src/loadgenerator
      - name: Push
        run: |
          docker push loadgenerator